name: lawflow
region: nyc
services:
  - name: lawflow-web
    dockerfile_path: Dockerfile
    github:
      repo: Linos-spec/lawflow
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "${db-lawflow.DATABASE_URL}"
      - key: NEXTAUTH_URL
        scope: RUN_TIME
        value: "https://lawflow-b8pcz.ondigitalocean.app"
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "rG7cSv3H+CvPN2l6Gwk5if0Kuo73CzwKrKLYUpPtOXo="
      - key: AUTH_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "rG7cSv3H+CvPN2l6Gwk5if0Kuo73CzwKrKLYUpPtOXo="
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: "your-openai-api-key"
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: "production"
databases:
  - name: db-lawflow
    engine: PG
    production: false
